name: Build iOS App

# Trigger workflow on push or PR to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # Change to your Flutter version

      # Step 3: Get dependencies
      - name: Flutter pub get
        run: flutter pub get

      # Step 4: Build iOS app
      - name: Build iOS release
        run: flutter build ios --release --no-codesign

      # Step 5: Upload built app as artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: iOS-App
          path: build/ios/iphoneos/Runner.app
